### ISSUE TITLE
TypeError: data.join is not a function

### ISSUE THREAD

**Issue by PatMyron** [mhlabs/cfn-diagram#16]
```bash
cfn-dia html -t ~/Documents/GitHub/cfn-python-lint/test/fixtures/templates/bad/resources_circular_dependency_2.yaml

TypeError: data.join is not a function
    at Object.dump (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/node_modules/yaml-cfn/index.js:39:24)
    at applyOverrides (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/node_modules/yaml-cfn/index.js:44:49)
    at Type.represent (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/node_modules/yaml-cfn/index.js:61:23)
    at detectType (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/node_modules/js-yaml/lib/js-yaml/dumper.js:695:26)
    at writeNode (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/node_modules/js-yaml/lib/js-yaml/dumper.js:720:5)
    at writeBlockMapping (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
    at writeNode (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
    at writeBlockMapping (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
    at writeNode (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
    at dump (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/node_modules/js-yaml/lib/js-yaml/dumper.js:840:7)
```
```yaml
Resources:
  Resource:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        !Sub ${Resource2}
  Resource2:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        !GetAtt Resource3.TopicName
  Resource3:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        !Ref Resource4
  Resource4:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Fn::Sub: ${Resource5}
  Resource5:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Fn::GetAtt: Resource6.TopicName
  Resource6:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Ref: Resource7
  Resource7:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        !Sub ${Resource8.TopicName}
  Resource8:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Fn::Sub: ${Resource9.TopicName}
  Resource9:
    DependsOn: Resource
    Type: AWS::SNS::Topic
```
(template from https://github.com/aws-cloudformation/cfn-python-lint/pull/1391, https://github.com/aws-cloudformation/cfn-python-lint/pull/1411)

**Comment by ljacobsson** [comment]
Thanks for reporting.

This error originates from the yaml-cfn parser.

You can only reference the atttribute using dot-notation when using the !GetAtt shorthand syntax. Changing [this](https://github.com/miparnisari/cfn-python-lint/blob/590c03fa113cc9cca12006cc59824cff9a4aec45/test/fixtures/templates/bad/resources_circular_dependency_2.yaml#L26) to `Fn::GetAtt: [ Resource6, TopicName]` or `!GetAtt Resource6.TopicName` will give you valid CloudFormation.

Please refer to the [docs for Fn::GetAtt](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html)

I see you're using connections to visualise `DependsOn`-relationships. That's a good idea and I'll add an issue for that!

**Comment by ljacobsson** [comment]
I'll close this. Please reopen if you disagree :-)

**Comment by PatMyron** [comment]
> will give you valid CloudFormation

This template successfully deploys, but maybe better filed downstream: https://github.com/gristlabs/yaml-cfn/issues
```yaml
Resources:
  Resource:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        !Sub ${Resource2}
  Resource2:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        !GetAtt Resource3.TopicName
  Resource3:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        !Ref Resource4
  Resource4:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Fn::Sub: ${Resource5}
  Resource5:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Fn::GetAtt: Resource6.TopicName
  Resource6:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Ref: Resource7
  Resource7:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        !Sub ${Resource8.TopicName}
  Resource8:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Fn::Sub: ${Resource9.TopicName}
  Resource9:
    # DependsOn: Resource
    Type: AWS::SNS::Topic
```
